import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import '../Content/ABCostumizations.css'
import '../Content/EbankITCss.css'
import '../Content/EbankITCss.min.css'
import '../Content/EbankITIECss.css'
import '../Content/EbankITIECss.min.css'
import '../Content/Site.css'
import '../Content/Teste.css'
import '../Content/bootstrap-theme.css'
import '../Content/bootstrap-theme.min.css'
import '../Content/bootstrap.css'
import '../Content/bootstrap.min.css'
import '../Content/bootstrapValidator.css'
import '../Content/bootstrapValidator.min.css'
import '../Content/custom-styles.css'
import '../Content/custom-styles.min.css'
import '../Content/ebankITMasterCss.css'
import '../Content/ebankITMasterCss.min.css'
import '../Content/font-awesome.css'
import '../Content/font-awesome.min.css'
import '../Content/main.css'
import '../Content/main.min.css'
import '../Content/marketing-area.css'
import '../Content/marketing-area.min.css'
import '../Content/upgrade/Site.css'
import '../Content/upgrade/bootstrap-theme.css'
import '../Content/upgrade/bootstrap-theme.min.css'
import '../Content/upgrade/bootstrap.css'
import '../Content/upgrade/bootstrap.min.css'
import App from './App.tsx'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
