<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Web.Website transitively brings in Web.Common / Core / Infrastructure -->
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="16.5.1" />
  </ItemGroup>

</Project>
