//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "abstractBackgroundImage"
	/// <summary>Abstract Background Image</summary>
	public partial interface IAbstractBackgroundImage : IPublishedContent
	{
		/// <summary>Image File</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IPublishedContent EbankItimageFile { get; }

		/// <summary>Use Overlay?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		bool EbankItuseOverlay { get; }
	}

	/// <summary>Abstract Background Image</summary>
	[PublishedModel("abstractBackgroundImage")]
	public partial class AbstractBackgroundImage : PublishedContentModel, IAbstractBackgroundImage
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "abstractBackgroundImage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AbstractBackgroundImage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public AbstractBackgroundImage(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Image File: Select image file. This image must be in the media.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITImageFile")]
		public IPublishedContent EbankItimageFile => GetEbankItimageFile(this);

		/// <summary>Static getter for Image File</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedContent GetEbankItimageFile(IAbstractBackgroundImage that) => that.Value<IPublishedContent>("ebankITImageFile");

		///<summary>
		/// Use Overlay?: If you set an image, you can use the overlay effect.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITUseOverlay")]
		public bool EbankItuseOverlay => GetEbankItuseOverlay(this);

		/// <summary>Static getter for Use Overlay?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static bool GetEbankItuseOverlay(IAbstractBackgroundImage that) => that.Value<bool>("ebankITUseOverlay");
	}
}
