//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Call Me Back</summary>
	[PublishedModel("callMeBack")]
	public partial class CallMeBack : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "callMeBack";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CallMeBack, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public CallMeBack(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Call Me Back - Cell Phone: Cell Phone Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("callMeBackCellPhone")]
		public string CallMeBackCellPhone => this.Value<string>("callMeBackCellPhone");

		///<summary>
		/// Call Me Back - Different Location
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("callMeBackDifferentLocation")]
		public bool CallMeBackDifferentLocation => this.Value<bool>("callMeBackDifferentLocation");

		///<summary>
		/// Call Me Back - ID Number: Identification Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("callMeBackIDNumber")]
		public string CallMeBackIdnumber => this.Value<string>("callMeBackIDNumber");

		///<summary>
		/// Call Me Back - Name: Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("callMeBackName")]
		public string CallMeBackName => this.Value<string>("callMeBackName");

		///<summary>
		/// Call Me Back - Surname: Surname
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("callMeBackSurname")]
		public string CallMeBackSurname => this.Value<string>("callMeBackSurname");

		///<summary>
		/// Contact Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("contactType")]
		public string ContactType => this.Value<string>("contactType");

		///<summary>
		/// Floating Form Setting
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("floatingFormSetting")]
		public IEnumerable<FloatingFormSetting> FloatingFormSetting => this.Value<IEnumerable<FloatingFormSetting>>("floatingFormSetting");

		///<summary>
		/// Product Id
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("productId")]
		public string ProductId => this.Value<string>("productId");

		///<summary>
		/// Product Identification
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("productIdentification")]
		public string ProductIdentification => this.Value<string>("productIdentification");

		///<summary>
		/// Product Subject
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("productSubject")]
		public string ProductSubject => this.Value<string>("productSubject");

		///<summary>
		/// Success Icon: An icon that shows up after the user successfully receives a call me back results
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("successIcon")]
		public IPublishedContent SuccessIcon => this.Value<IPublishedContent>("successIcon");
	}
}
