//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Campaign</summary>
	[PublishedModel("campaign")]
	public partial class Campaign : PublishedContentModel, INCfloatingForm, IPageSettings, ISearchEngine
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "campaign";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Campaign, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Campaign(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Application Description: Description on how the user can apply
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("applicationDescription")]
		public IHtmlString ApplicationDescription => this.Value<IHtmlString>("applicationDescription");

		///<summary>
		/// Apply Now Button Label: Allows the user to add a description on the button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("applyNowButtonLabel")]
		public string ApplyNowButtonLabel => this.Value<string>("applyNowButtonLabel");

		///<summary>
		/// ApplyNowLink: Enter the link to where the page must point to.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("applyNowLink")]
		public IPublishedContent ApplyNowLink => this.Value<IPublishedContent>("applyNowLink");

		///<summary>
		/// Campaign Hero Button Label
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("campaignHeroButtonLabel")]
		public string CampaignHeroButtonLabel => this.Value<string>("campaignHeroButtonLabel");

		///<summary>
		/// Campaign Hero Button Redirect Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("campaignHeroButtonRedirectLink")]
		public string CampaignHeroButtonRedirectLink => this.Value<string>("campaignHeroButtonRedirectLink");

		///<summary>
		/// Campaign Hero Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("campaignHeroDescription")]
		public string CampaignHeroDescription => this.Value<string>("campaignHeroDescription");

		///<summary>
		/// Campaign Hero Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("campaignHeroHeadline")]
		public string CampaignHeroHeadline => this.Value<string>("campaignHeroHeadline");

		///<summary>
		/// Campaign Hero Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("campaignHeroImage")]
		public IPublishedContent CampaignHeroImage => this.Value<IPublishedContent>("campaignHeroImage");

		///<summary>
		/// Campaign Product Info
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("campaignProductInfo")]
		public IEnumerable<StructureProductInformation> CampaignProductInfo => this.Value<IEnumerable<StructureProductInformation>>("campaignProductInfo");

		///<summary>
		/// Campaign Testimonials
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("campaignTestimonials")]
		public IEnumerable<StructureAvatarNameStory> CampaignTestimonials => this.Value<IEnumerable<StructureAvatarNameStory>>("campaignTestimonials");

		///<summary>
		/// Credit Insured Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("creditInsuredDescription")]
		public string CreditInsuredDescription => this.Value<string>("creditInsuredDescription");

		///<summary>
		/// Credit Insured Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("creditInsuredImage")]
		public IPublishedContent CreditInsuredImage => this.Value<IPublishedContent>("creditInsuredImage");

		///<summary>
		/// Credit Insured Legal Statement
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("creditInsuredLegalStatement")]
		public string CreditInsuredLegalStatement => this.Value<string>("creditInsuredLegalStatement");

		///<summary>
		/// Credit Insured Options
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("creditInsuredOptions")]
		public IEnumerable<Umbraco.Web.Models.Link> CreditInsuredOptions => this.Value<IEnumerable<Umbraco.Web.Models.Link>>("creditInsuredOptions");

		///<summary>
		/// Download Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("downloadDescription")]
		public string DownloadDescription => this.Value<string>("downloadDescription");

		///<summary>
		/// Download Files
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("downloadFiles")]
		public IEnumerable<StructureTextAndButton> DownloadFiles => this.Value<IEnumerable<StructureTextAndButton>>("downloadFiles");

		///<summary>
		/// Download Legal Statement
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("downloadLegalStatement")]
		public string DownloadLegalStatement => this.Value<string>("downloadLegalStatement");

		///<summary>
		/// Featured Products
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("featuredProducts")]
		public IEnumerable<StructureFeaturedProduct> FeaturedProducts => this.Value<IEnumerable<StructureFeaturedProduct>>("featuredProducts");

		///<summary>
		/// howToApplyTitle: Enter the how to apply title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("howToApplyTitle")]
		public string HowToApplyTitle => this.Value<string>("howToApplyTitle");

		///<summary>
		/// In Page Linking
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("inPageLinking")]
		public IEnumerable<Umbraco.Web.Models.Link> InPageLinking => this.Value<IEnumerable<Umbraco.Web.Models.Link>>("inPageLinking");

		///<summary>
		/// Call me back button text: Text in the button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("callMeBackButtonText")]
		public string CallMeBackButtonText => NCfloatingForm.GetCallMeBackButtonText(this);

		///<summary>
		/// Call me back visible: Hide or show call me back button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("callMeBackVisible")]
		public bool CallMeBackVisible => NCfloatingForm.GetCallMeBackVisible(this);

		///<summary>
		/// External link text: Text for the external link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("externalLabel")]
		public string ExternalLabel => NCfloatingForm.GetExternalLabel(this);

		///<summary>
		/// External link visible: Hide or show external links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("externalLinkVisible")]
		public bool ExternalLinkVisible => NCfloatingForm.GetExternalLinkVisible(this);

		///<summary>
		/// External link: External links from the website
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("linkExternal")]
		public string LinkExternal => NCfloatingForm.GetLinkExternal(this);

		///<summary>
		/// Open As Default?: Open the floating form on page load.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("openAsDefault")]
		public bool OpenAsDefault => NCfloatingForm.GetOpenAsDefault(this);

		///<summary>
		/// Product Identification: For google analytics tracking
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("productIdentification")]
		public string ProductIdentification => NCfloatingForm.GetProductIdentification(this);

		///<summary>
		/// Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("title")]
		public string Title => NCfloatingForm.GetTitle(this);

		///<summary>
		/// Contact Type: Contact type information
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("contactType")]
		public string ContactType => PageSettings.GetContactType(this);

		///<summary>
		/// Floating Form
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("floatingForm")]
		public NCfloatingForm FloatingForm => PageSettings.GetFloatingForm(this);

		///<summary>
		/// productID: ID to uniquely Identify products
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("productID")]
		public string ProductID => PageSettings.GetProductID(this);

		///<summary>
		/// Product Subject: product subject for submittion
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("productSubject")]
		public string ProductSubject => PageSettings.GetProductSubject(this);

		///<summary>
		/// Alternate Image Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("alternateImageText")]
		public string AlternateImageText => SearchEngine.GetAlternateImageText(this);

		///<summary>
		/// Description_tag: This field will not be shown anywhere, it will be used in google indexing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("description_tag")]
		public string Description_tag => SearchEngine.GetDescription_tag(this);

		///<summary>
		/// Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("image")]
		public IPublishedContent Image => SearchEngine.GetImage(this);

		///<summary>
		/// keywords_tag: This field will not be shown anywhere, it will be used in google indexing {meta
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("keywords_tag")]
		public string Keywords_tag => SearchEngine.GetKeywords_tag(this);

		///<summary>
		/// robots_tag: Tag robots meta tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("robots_tag")]
		public string Robots_tag => SearchEngine.GetRobots_tag(this);

		///<summary>
		/// Security: Add yes if this page requires security and has a form
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("security")]
		public string Security => SearchEngine.GetSecurity(this);

		///<summary>
		/// title_tag: This field will not be shown anywhere, it will be used in google indexing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("title_tag")]
		public string Title_tag => SearchEngine.GetTitle_tag(this);
	}
}
