//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Described Card</summary>
	[PublishedModel("describedCard")]
	public partial class DescribedCard : PublishedElementModel, INCcard
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "describedCard";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DescribedCard, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public DescribedCard(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Main Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("mainDescription")]
		public IHtmlString MainDescription => this.Value<IHtmlString>("mainDescription");

		///<summary>
		/// Main Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("mainTitle")]
		public string MainTitle => this.Value<string>("mainTitle");

		///<summary>
		/// Abstract Button: A button/ActionLink within a card
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("abstractButton")]
		public string AbstractButton => NCcard.GetAbstractButton(this);

		///<summary>
		/// Abstract It: Button Link To External
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("abstractIt")]
		public string AbstractIt => NCcard.GetAbstractIt(this);

		///<summary>
		/// Image List And Descriptions: Image List And Descriptions
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("imageListAndDescriptions")]
		public IEnumerable<NCitemWithDescription> ImageListAndDescriptions => NCcard.GetImageListAndDescriptions(this);

		///<summary>
		/// Medium Description: This is a control for extending description on the page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("mediumDescription")]
		public IHtmlString MediumDescription => NCcard.GetMediumDescription(this);

		///<summary>
		/// Card Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("nCcardDescription")]
		public string NCcardDescription => NCcard.GetNCcardDescription(this);

		///<summary>
		/// Card Icon
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("nCcardIcon")]
		public IPublishedContent NCcardIcon => NCcard.GetNCcardIcon(this);

		///<summary>
		/// NC Card Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("nCcardTitle")]
		public string NCcardTitle => NCcard.GetNCcardTitle(this);

		///<summary>
		/// Long Description: Rich Textbox for descriptions that have mixed media and are long
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("nClongDescription")]
		public IHtmlString NClongDescription => NCcard.GetNClongDescription(this);
	}
}
