//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "ebankITOverlay"
	/// <summary>Overlay</summary>
	public partial interface IEbankItoverlay : IPublishedContent
	{
		/// <summary>Content Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string EbankItoverlayContentText { get; }

		/// <summary>Context Align</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string EbankItoverlayContentTextAlign { get; }

		/// <summary>Overlay Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string EbankItoverlayType { get; }

		/// <summary>Use hover effect?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		bool EbankItoverlayUseHoverEffect { get; }

		/// <summary>Use Button?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		bool EbankItuseOverlayButton { get; }
	}

	/// <summary>Overlay</summary>
	[PublishedModel("ebankITOverlay")]
	public partial class EbankItoverlay : PublishedContentModel, IEbankItoverlay
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "ebankITOverlay";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EbankItoverlay, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public EbankItoverlay(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Content Text: Enter text to show in overlay. (Max Length:100)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITOverlayContentText")]
		public string EbankItoverlayContentText => GetEbankItoverlayContentText(this);

		/// <summary>Static getter for Content Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetEbankItoverlayContentText(IEbankItoverlay that) => that.Value<string>("ebankITOverlayContentText");

		///<summary>
		/// Context Align: Select the alignment you want to align the overlay content text (default value Left).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITOverlayContentTextAlign")]
		public string EbankItoverlayContentTextAlign => GetEbankItoverlayContentTextAlign(this);

		/// <summary>Static getter for Context Align</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetEbankItoverlayContentTextAlign(IEbankItoverlay that) => that.Value<string>("ebankITOverlayContentTextAlign");

		///<summary>
		/// Overlay Type: Select the overlay type color.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITOverlayType")]
		public string EbankItoverlayType => GetEbankItoverlayType(this);

		/// <summary>Static getter for Overlay Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetEbankItoverlayType(IEbankItoverlay that) => that.Value<string>("ebankITOverlayType");

		///<summary>
		/// Use hover effect?: If checked, the color is changed when the cursor overlaps the overlay component. Otherwise, the overlay color is always the same, (according to the selected Overlay Type and only in desktop environment).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankIToverlayUseHoverEffect")]
		public bool EbankItoverlayUseHoverEffect => GetEbankItoverlayUseHoverEffect(this);

		/// <summary>Static getter for Use hover effect?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static bool GetEbankItoverlayUseHoverEffect(IEbankItoverlay that) => that.Value<bool>("ebankIToverlayUseHoverEffect");

		///<summary>
		/// Use Button?: Check to use one button inside the overlay. If checked, please configure button properties in tab "Button".
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITUseOverlayButton")]
		public bool EbankItuseOverlayButton => GetEbankItuseOverlayButton(this);

		/// <summary>Static getter for Use Button?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static bool GetEbankItuseOverlayButton(IEbankItoverlay that) => that.Value<bool>("ebankITUseOverlayButton");
	}
}
