//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Generic Contact Form</summary>
	[PublishedModel("ebankITGenericContactForm")]
	public partial class EbankItgenericContactForm : PublishedContentModel, IEbankItgeneralProperties, IEbankItsectionSettings, IFormSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "ebankITGenericContactForm";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EbankItgenericContactForm, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public EbankItgenericContactForm(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Content: The first section of text in page or section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITContent")]
		public IHtmlString EbankItcontent => EbankItgeneralProperties.GetEbankItcontent(this);

		///<summary>
		/// Title: Title of page or section  (Max Length:150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITTitle")]
		public string EbankIttitle => EbankItgeneralProperties.GetEbankIttitle(this);

		///<summary>
		/// Background Color: Section background color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITColorBackground")]
		public string EbankItcolorBackground => EbankItsectionSettings.GetEbankItcolorBackground(this);

		///<summary>
		/// Content Color: Section content color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITContentColor")]
		public string EbankItcontentColor => EbankItsectionSettings.GetEbankItcontentColor(this);

		///<summary>
		/// Remove Bottom Margin?: If checked, Remove the margins  top this section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITRemoveMarginBottom")]
		public bool EbankItremoveMarginBottom => EbankItsectionSettings.GetEbankItremoveMarginBottom(this);

		///<summary>
		/// Remove Top Margin?: If checked, remove the margins  top this section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITRemoveMarginTop")]
		public bool EbankItremoveMarginTop => EbankItsectionSettings.GetEbankItremoveMarginTop(this);

		///<summary>
		/// Title Color: Section title color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITTitleTextColor")]
		public string EbankIttitleTextColor => EbankItsectionSettings.GetEbankIttitleTextColor(this);

		///<summary>
		/// Button Label: This label will appear in submit button and fly out tab.  (This field is mandatory /Max Length:15)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankitButtonLabel")]
		public string EbankitButtonLabel => FormSettings.GetEbankitButtonLabel(this);

		///<summary>
		/// Error Message: Message will be appear when the form is not submitted successfully. (This filed is mandatory/ Max Length:150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankitErrorMessage")]
		public string EbankitErrorMessage => FormSettings.GetEbankitErrorMessage(this);

		///<summary>
		/// Main Subject: This field will be sent as part of contract center subject (This Field is mandatory)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITMainSubjectEmail")]
		public string EbankItmainSubjectEmail => FormSettings.GetEbankItmainSubjectEmail(this);

		///<summary>
		/// Save Before Submit?: If this field is check, before the user click in submit button, the form will be save. If you fill this field, please fill next field 'Save Before Submit Interval'
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankitSaveBeforeSubmit")]
		public bool EbankitSaveBeforeSubmit => FormSettings.GetEbankitSaveBeforeSubmit(this);

		///<summary>
		/// Save Before Submit Interval: Time, in seconds for the form submit without the user click in submit button.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankitSaveBeforeSubmitInterval")]
		public int EbankitSaveBeforeSubmitInterval => FormSettings.GetEbankitSaveBeforeSubmitInterval(this);

		///<summary>
		/// Subject Label: This label will be appear before the dropdown with all Subject Values. If you fill this field, please fill next field 'Subject Values'  (Max Length:150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankitSubjectLabel")]
		public string EbankitSubjectLabel => FormSettings.GetEbankitSubjectLabel(this);

		///<summary>
		/// Subject Values: Fill in this field with all the values ​​in the dropdown
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITSubjectValues")]
		public string EbankItsubjectValues => FormSettings.GetEbankItsubjectValues(this);

		///<summary>
		/// Success Message: Message will be appear when the form is submitted successfully. (This filed is  mandatory/ Max Length:150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankitSuccessMessage")]
		public string EbankitSuccessMessage => FormSettings.GetEbankitSuccessMessage(this);
	}
}
