//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Logo</summary>
	[PublishedModel("ebankITLogoSettings")]
	public partial class EbankItlogoSettings : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "ebankITLogoSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EbankItlogoSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public EbankItlogoSettings(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Alt Logo: The text that will appear in the logo alt (Max Length:150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITAltLogo")]
		public string EbankItaltLogo => this.Value<string>("ebankITAltLogo");

		///<summary>
		/// Alt Logo Small: The text that will appear in the logo  alt (Max Length:150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITAltLogoSmall")]
		public string EbankItaltLogoSmall => this.Value<string>("ebankITAltLogoSmall");

		///<summary>
		/// Favicon: Suggested size: 310x310px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITFavicon")]
		public IPublishedContent EbankItfavicon => this.Value<IPublishedContent>("ebankITFavicon");

		///<summary>
		/// Logo: The site logo to be used on all pages when you use the desktop or tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITLogo")]
		public IPublishedContent EbankItlogo => this.Value<IPublishedContent>("ebankITLogo");

		///<summary>
		/// Site Name: The site name is essentially the browser title for the home page. This will also be appended as a suffix to all  other pages. (Max Length:150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITSiteName")]
		public string EbankItsiteName => this.Value<string>("ebankITSiteName");

		///<summary>
		/// Small Logo: The site logo to be used on all pages when you use the mobile phones
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITSmallLogo")]
		public IPublishedContent EbankItsmallLogo => this.Value<IPublishedContent>("ebankITSmallLogo");
	}
}
