//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Site Settings</summary>
	[PublishedModel("ebanKITSiteSettings")]
	public partial class EbanKitsiteSettings : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "ebanKITSiteSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EbanKitsiteSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public EbanKitsiteSettings(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Button Apply Now in Menu: If it is selected the button 'Apply now' will appear in the menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITButtonApplyNowInMenu")]
		public bool EbankItbuttonApplyNowInMenu => this.Value<bool>("ebankITButtonApplyNowInMenu");

		///<summary>
		/// Button Login in Menu: If it is selected the button 'Login' will appear in the menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITButtonLoginInMenu")]
		public bool EbankItbuttonLoginInMenu => this.Value<bool>("ebankITButtonLoginInMenu");

		///<summary>
		/// Apply Now: External Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITLinkApplyNow")]
		public string EbankItlinkApplyNow => this.Value<string>("ebankITLinkApplyNow");

		///<summary>
		/// Link login loan and credit
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITLoginLoanCreditLink")]
		public string EbankItloginLoanCreditLink => this.Value<string>("ebankITLoginLoanCreditLink");

		///<summary>
		/// Link login save and invest: External Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITLoginSaveInvestLink")]
		public string EbankItloginSaveInvestLink => this.Value<string>("ebankITLoginSaveInvestLink");
	}
}
