//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "ebankITAbstractButton"
	/// <summary>Abstract Button</summary>
	public partial interface IEbankItabstractButton : IPublishedContent
	{
		/// <summary>External Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string EbankItbuttonExternalLink { get; }

		/// <summary>Internal Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IPublishedContent EbankItbuttonInternalLink { get; }

		/// <summary>Open new tab?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		bool EbankItbuttonOpenNewTab { get; }

		/// <summary>Button Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string EbankItbuttonText { get; }

		/// <summary>External Link Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string ExternalLinkType { get; }
	}

	/// <summary>Abstract Button</summary>
	[PublishedModel("ebankITAbstractButton")]
	public partial class EbankItabstractButton : PublishedContentModel, IEbankItabstractButton
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "ebankITAbstractButton";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EbankItabstractButton, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public EbankItabstractButton(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// External Link: Optional link to an external page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITButtonExternalLink")]
		public string EbankItbuttonExternalLink => GetEbankItbuttonExternalLink(this);

		/// <summary>Static getter for External Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetEbankItbuttonExternalLink(IEbankItabstractButton that) => that.Value<string>("ebankITButtonExternalLink");

		///<summary>
		/// Internal Link: Link to a page on this site.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITButtonInternalLink")]
		public IPublishedContent EbankItbuttonInternalLink => GetEbankItbuttonInternalLink(this);

		/// <summary>Static getter for Internal Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedContent GetEbankItbuttonInternalLink(IEbankItabstractButton that) => that.Value<IPublishedContent>("ebankITButtonInternalLink");

		///<summary>
		/// Open new tab?: Check to open the button link in a new browser tab.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITButtonOpenNewTab")]
		public bool EbankItbuttonOpenNewTab => GetEbankItbuttonOpenNewTab(this);

		/// <summary>Static getter for Open new tab?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static bool GetEbankItbuttonOpenNewTab(IEbankItabstractButton that) => that.Value<bool>("ebankITButtonOpenNewTab");

		///<summary>
		/// Button Text: The text is shown in the button. (Max Length:16)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITButtonText")]
		public string EbankItbuttonText => GetEbankItbuttonText(this);

		/// <summary>Static getter for Button Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetEbankItbuttonText(IEbankItabstractButton that) => that.Value<string>("ebankITButtonText");

		///<summary>
		/// External Link Type: Select the page you want to redirect to and the URL will be resolved based on the selected type.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("externalLinkType")]
		public string ExternalLinkType => GetExternalLinkType(this);

		/// <summary>Static getter for External Link Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetExternalLinkType(IEbankItabstractButton that) => that.Value<string>("externalLinkType");
	}
}
