//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "ebankITSectionSettings"
	/// <summary>Section Settings</summary>
	public partial interface IEbankItsectionSettings : IPublishedContent
	{
		/// <summary>Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string EbankItcolorBackground { get; }

		/// <summary>Content Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string EbankItcontentColor { get; }

		/// <summary>Remove Bottom Margin?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		bool EbankItremoveMarginBottom { get; }

		/// <summary>Remove Top Margin?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		bool EbankItremoveMarginTop { get; }

		/// <summary>Title Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string EbankIttitleTextColor { get; }
	}

	/// <summary>Section Settings</summary>
	[PublishedModel("ebankITSectionSettings")]
	public partial class EbankItsectionSettings : PublishedContentModel, IEbankItsectionSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "ebankITSectionSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EbankItsectionSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public EbankItsectionSettings(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Background Color: Section background color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITColorBackground")]
		public string EbankItcolorBackground => GetEbankItcolorBackground(this);

		/// <summary>Static getter for Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetEbankItcolorBackground(IEbankItsectionSettings that) => that.Value<string>("ebankITColorBackground");

		///<summary>
		/// Content Color: Section content color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITContentColor")]
		public string EbankItcontentColor => GetEbankItcontentColor(this);

		/// <summary>Static getter for Content Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetEbankItcontentColor(IEbankItsectionSettings that) => that.Value<string>("ebankITContentColor");

		///<summary>
		/// Remove Bottom Margin?: If checked, Remove the margins  top this section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITRemoveMarginBottom")]
		public bool EbankItremoveMarginBottom => GetEbankItremoveMarginBottom(this);

		/// <summary>Static getter for Remove Bottom Margin?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static bool GetEbankItremoveMarginBottom(IEbankItsectionSettings that) => that.Value<bool>("ebankITRemoveMarginBottom");

		///<summary>
		/// Remove Top Margin?: If checked, remove the margins  top this section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITRemoveMarginTop")]
		public bool EbankItremoveMarginTop => GetEbankItremoveMarginTop(this);

		/// <summary>Static getter for Remove Top Margin?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static bool GetEbankItremoveMarginTop(IEbankItsectionSettings that) => that.Value<bool>("ebankITRemoveMarginTop");

		///<summary>
		/// Title Color: Section title color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITTitleTextColor")]
		public string EbankIttitleTextColor => GetEbankIttitleTextColor(this);

		/// <summary>Static getter for Title Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetEbankIttitleTextColor(IEbankItsectionSettings that) => that.Value<string>("ebankITTitleTextColor");
	}
}
