//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Image HomePage</summary>
	[PublishedModel("ebanKITImageHomePage")]
	public partial class EbanKitimageHomePage : PublishedContentModel, IEbankItabstractBackgroundImage, IEbankItgeneralProperties, IEbankItlink
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "ebanKITImageHomePage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EbanKitimageHomePage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public EbanKitimageHomePage(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Image: This image must be in the media
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITImage")]
		public IPublishedContent EbankItimage => EbankItabstractBackgroundImage.GetEbankItimage(this);

		///<summary>
		/// Use Overlay: If you have set a background image, you can use a dark or
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebanKITUseOverlay")]
		public bool EbanKituseOverlay => EbankItabstractBackgroundImage.GetEbanKituseOverlay(this);

		///<summary>
		/// Content: The first section of text in page or section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITContent")]
		public IHtmlString EbankItcontent => EbankItgeneralProperties.GetEbankItcontent(this);

		///<summary>
		/// Title: Title of page or section  (Max Length:150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITTitle")]
		public string EbankIttitle => EbankItgeneralProperties.GetEbankIttitle(this);

		///<summary>
		/// Anchors Internal Link: The anchor the page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITAnchorsInternalLink")]
		public string EbankItanchorsInternalLink => EbankItlink.GetEbankItanchorsInternalLink(this);

		///<summary>
		/// Document: The document that will open. This document must be in the media
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITDocument")]
		public IPublishedContent EbankItdocument => EbankItlink.GetEbankItdocument(this);

		///<summary>
		/// External Link: Optional link to an external page. (http://website.com).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITExternalLink")]
		public string EbankItexternalLink => EbankItlink.GetEbankItexternalLink(this);

		///<summary>
		/// Internal Link: Link to a page on your site
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITInternalLink")]
		public IPublishedContent EbankItinternalLink => EbankItlink.GetEbankItinternalLink(this);

		///<summary>
		/// Text: This text only is shown in a List Links and the footer (Max length: 150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITLinkTitle")]
		public string EbankItlinkTitle => EbankItlink.GetEbankItlinkTitle(this);

		///<summary>
		/// Open New Tab: If you want the link open in new tab, you need selected this
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITOpenNewTab")]
		public bool EbankItopenNewTab => EbankItlink.GetEbankItopenNewTab(this);
	}
}
