//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "ebankITNavigation"
	/// <summary>Navigation</summary>
	public partial interface IEbankItnavigation : IPublishedContent
	{
		/// <summary>Icon</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IPublishedContent EbankIticonMenu { get; }

		/// <summary>Is Investors</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		bool EbankItisInvestors { get; }

		/// <summary>Menu</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		bool EbankItmenu { get; }

		/// <summary>Without Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		bool EbankItwithoutLink { get; }

		/// <summary>Hide In Xml Sitemap</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		bool HideInXmlSitemap { get; }
	}

	/// <summary>Navigation</summary>
	[PublishedModel("ebankITNavigation")]
	public partial class EbankItnavigation : PublishedContentModel, IEbankItnavigation
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "ebankITNavigation";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EbankItnavigation, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public EbankItnavigation(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Icon: Icon will appear in sub-menu. This icon must be in the media.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITIconMenu")]
		public IPublishedContent EbankIticonMenu => GetEbankIticonMenu(this);

		/// <summary>Static getter for Icon</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedContent GetEbankIticonMenu(IEbankItnavigation that) => that.Value<IPublishedContent>("ebankITIconMenu");

		///<summary>
		/// Is Investors: If this page only will appear when we select menu "investors", you must be select this field
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITIsInvestors")]
		public bool EbankItisInvestors => GetEbankItisInvestors(this);

		/// <summary>Static getter for Is Investors</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static bool GetEbankItisInvestors(IEbankItnavigation that) => that.Value<bool>("ebankITIsInvestors");

		///<summary>
		/// Menu: If this page will appear in the menu, you must be select this field
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITMenu")]
		public bool EbankItmenu => GetEbankItmenu(this);

		/// <summary>Static getter for Menu</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static bool GetEbankItmenu(IEbankItnavigation that) => that.Value<bool>("ebankITMenu");

		///<summary>
		/// Without Link: If this page will appear in menu, but don't have link, you must be select this field
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITWithoutLink")]
		public bool EbankItwithoutLink => GetEbankItwithoutLink(this);

		/// <summary>Static getter for Without Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static bool GetEbankItwithoutLink(IEbankItnavigation that) => that.Value<bool>("ebankITWithoutLink");

		///<summary>
		/// Hide In Xml Sitemap: If true this node will not be included in the website sitemap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("hideInXmlSitemap")]
		public bool HideInXmlSitemap => GetHideInXmlSitemap(this);

		/// <summary>Static getter for Hide In Xml Sitemap</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static bool GetHideInXmlSitemap(IEbankItnavigation that) => that.Value<bool>("hideInXmlSitemap");
	}
}
