//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Banner Start Learning</summary>
	[PublishedModel("ebankITBannerStartLearning")]
	public partial class EbankItbannerStartLearning : PublishedContentModel, IEbankItgeneralProperties, IEbankItsectionSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "ebankITBannerStartLearning";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EbankItbannerStartLearning, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public EbankItbannerStartLearning(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Internal Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITInternalLink")]
		public IPublishedContent EbankItinternalLink => this.Value<IPublishedContent>("ebankITInternalLink");

		///<summary>
		/// Content: The first section of text in page or section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITContent")]
		public IHtmlString EbankItcontent => EbankItgeneralProperties.GetEbankItcontent(this);

		///<summary>
		/// Title: Title of page or section  (Max Length:150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITTitle")]
		public string EbankIttitle => EbankItgeneralProperties.GetEbankIttitle(this);

		///<summary>
		/// Background Color: Section background color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITColorBackground")]
		public string EbankItcolorBackground => EbankItsectionSettings.GetEbankItcolorBackground(this);

		///<summary>
		/// Content Color: Section content color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITContentColor")]
		public string EbankItcontentColor => EbankItsectionSettings.GetEbankItcontentColor(this);

		///<summary>
		/// Remove Bottom Margin?: If checked, Remove the margins  top this section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITRemoveMarginBottom")]
		public bool EbankItremoveMarginBottom => EbankItsectionSettings.GetEbankItremoveMarginBottom(this);

		///<summary>
		/// Remove Top Margin?: If checked, remove the margins  top this section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITRemoveMarginTop")]
		public bool EbankItremoveMarginTop => EbankItsectionSettings.GetEbankItremoveMarginTop(this);

		///<summary>
		/// Title Color: Section title color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITTitleTextColor")]
		public string EbankIttitleTextColor => EbankItsectionSettings.GetEbankIttitleTextColor(this);
	}
}
