//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "ebankITVideo"
	/// <summary>Video</summary>
	public partial interface IEbankItvideo : IPublishedContent
	{
		/// <summary>Play infinitely looping?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		bool EbankItplayInfinitelyLooping { get; }

		/// <summary>Preloading Image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IPublishedContent EbankItpreImageVideo { get; }

		/// <summary>Video File</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IPublishedContent EbankItvideoFile { get; }

		/// <summary>Video player with sound?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		bool EbankItvideoPlayerWithSound { get; }
	}

	/// <summary>Video</summary>
	[PublishedModel("ebankITVideo")]
	public partial class EbankItvideo : PublishedContentModel, IEbankItvideo
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "ebankITVideo";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EbankItvideo, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public EbankItvideo(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Play infinitely looping?: If checked, the video is reproduced infilitely. Otherwise, the video plays only once.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITPlayInfinitelyLooping")]
		public bool EbankItplayInfinitelyLooping => GetEbankItplayInfinitelyLooping(this);

		/// <summary>Static getter for Play infinitely looping?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static bool GetEbankItplayInfinitelyLooping(IEbankItvideo that) => that.Value<bool>("ebankITPlayInfinitelyLooping");

		///<summary>
		/// Preloading Image: Select a video preloading  image. This image must be in the media
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITPreImageVideo")]
		public IPublishedContent EbankItpreImageVideo => GetEbankItpreImageVideo(this);

		/// <summary>Static getter for Preloading Image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedContent GetEbankItpreImageVideo(IEbankItvideo that) => that.Value<IPublishedContent>("ebankITPreImageVideo");

		///<summary>
		/// Video File: Select the video file (with mp4 file format). This field must be in the media
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITVideoFile")]
		public IPublishedContent EbankItvideoFile => GetEbankItvideoFile(this);

		/// <summary>Static getter for Video File</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedContent GetEbankItvideoFile(IEbankItvideo that) => that.Value<IPublishedContent>("ebankITVideoFile");

		///<summary>
		/// Video player with sound?: If checked, the video is reproduced with sound. Otherwise, the video is muted.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITVideoPlayerWithSound")]
		public bool EbankItvideoPlayerWithSound => GetEbankItvideoPlayerWithSound(this);

		/// <summary>Static getter for Video player with sound?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static bool GetEbankItvideoPlayerWithSound(IEbankItvideo that) => that.Value<bool>("ebankITVideoPlayerWithSound");
	}
}
