//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "ebankITLink"
	/// <summary>Link</summary>
	public partial interface IEbankItlink : IPublishedElement
	{
		/// <summary>Anchors Internal Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string EbankItanchorsInternalLink { get; }

		/// <summary>Document</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IPublishedContent EbankItdocument { get; }

		/// <summary>External Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string EbankItexternalLink { get; }

		/// <summary>Internal Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IPublishedContent EbankItinternalLink { get; }

		/// <summary>Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string EbankItlinkTitle { get; }

		/// <summary>Open New Tab</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		bool EbankItopenNewTab { get; }
	}

	/// <summary>Link</summary>
	[PublishedModel("ebankITLink")]
	public partial class EbankItlink : PublishedElementModel, IEbankItlink
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "ebankITLink";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EbankItlink, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public EbankItlink(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Anchors Internal Link: The anchor the page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITAnchorsInternalLink")]
		public string EbankItanchorsInternalLink => GetEbankItanchorsInternalLink(this);

		/// <summary>Static getter for Anchors Internal Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetEbankItanchorsInternalLink(IEbankItlink that) => that.Value<string>("ebankITAnchorsInternalLink");

		///<summary>
		/// Document: The document that will open. This document must be in the media
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITDocument")]
		public IPublishedContent EbankItdocument => GetEbankItdocument(this);

		/// <summary>Static getter for Document</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedContent GetEbankItdocument(IEbankItlink that) => that.Value<IPublishedContent>("ebankITDocument");

		///<summary>
		/// External Link: Optional link to an external page. (http://website.com).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITExternalLink")]
		public string EbankItexternalLink => GetEbankItexternalLink(this);

		/// <summary>Static getter for External Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetEbankItexternalLink(IEbankItlink that) => that.Value<string>("ebankITExternalLink");

		///<summary>
		/// Internal Link: Link to a page on your site
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITInternalLink")]
		public IPublishedContent EbankItinternalLink => GetEbankItinternalLink(this);

		/// <summary>Static getter for Internal Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedContent GetEbankItinternalLink(IEbankItlink that) => that.Value<IPublishedContent>("ebankITInternalLink");

		///<summary>
		/// Text: This text only is shown in a List Links and the footer (Max length: 150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITLinkTitle")]
		public string EbankItlinkTitle => GetEbankItlinkTitle(this);

		/// <summary>Static getter for Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetEbankItlinkTitle(IEbankItlink that) => that.Value<string>("ebankITLinkTitle");

		///<summary>
		/// Open New Tab: If you want the link open in new tab, you need selected this
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITOpenNewTab")]
		public bool EbankItopenNewTab => GetEbankItopenNewTab(this);

		/// <summary>Static getter for Open New Tab</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static bool GetEbankItopenNewTab(IEbankItlink that) => that.Value<bool>("ebankITOpenNewTab");
	}
}
