//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Slider Image</summary>
	[PublishedModel("ebankITSliderImage")]
	public partial class EbankItsliderImage : PublishedContentModel, IAbstractBackgroundImage, IEbankItabstractButton, IEbankItoverlay
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "ebankITSliderImage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EbankItsliderImage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public EbankItsliderImage(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Image File: Select image file. This image must be in the media.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITImageFile")]
		public IPublishedContent EbankItimageFile => AbstractBackgroundImage.GetEbankItimageFile(this);

		///<summary>
		/// Use Overlay?: If you set an image, you can use the overlay effect.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITUseOverlay")]
		public bool EbankItuseOverlay => AbstractBackgroundImage.GetEbankItuseOverlay(this);

		///<summary>
		/// External Link: Optional link to an external page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITButtonExternalLink")]
		public string EbankItbuttonExternalLink => EbankItabstractButton.GetEbankItbuttonExternalLink(this);

		///<summary>
		/// Internal Link: Link to a page on this site.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITButtonInternalLink")]
		public IPublishedContent EbankItbuttonInternalLink => EbankItabstractButton.GetEbankItbuttonInternalLink(this);

		///<summary>
		/// Open new tab?: Check to open the button link in a new browser tab.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITButtonOpenNewTab")]
		public bool EbankItbuttonOpenNewTab => EbankItabstractButton.GetEbankItbuttonOpenNewTab(this);

		///<summary>
		/// Button Text: The text is shown in the button. (Max Length:16)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITButtonText")]
		public string EbankItbuttonText => EbankItabstractButton.GetEbankItbuttonText(this);

		///<summary>
		/// External Link Type: Select the page you want to redirect to and the URL will be resolved based on the selected type.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("externalLinkType")]
		public string ExternalLinkType => EbankItabstractButton.GetExternalLinkType(this);

		///<summary>
		/// Content Text: Enter text to show in overlay. (Max Length:100)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITOverlayContentText")]
		public string EbankItoverlayContentText => EbankItoverlay.GetEbankItoverlayContentText(this);

		///<summary>
		/// Context Align: Select the alignment you want to align the overlay content text (default value Left).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITOverlayContentTextAlign")]
		public string EbankItoverlayContentTextAlign => EbankItoverlay.GetEbankItoverlayContentTextAlign(this);

		///<summary>
		/// Overlay Type: Select the overlay type color.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITOverlayType")]
		public string EbankItoverlayType => EbankItoverlay.GetEbankItoverlayType(this);

		///<summary>
		/// Use hover effect?: If checked, the color is changed when the cursor overlaps the overlay component. Otherwise, the overlay color is always the same, (according to the selected Overlay Type and only in desktop environment).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankIToverlayUseHoverEffect")]
		public bool EbankItoverlayUseHoverEffect => EbankItoverlay.GetEbankItoverlayUseHoverEffect(this);

		///<summary>
		/// Use Button?: Check to use one button inside the overlay. If checked, please configure button properties in tab "Button".
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITUseOverlayButton")]
		public bool EbankItuseOverlayButton => EbankItoverlay.GetEbankItuseOverlayButton(this);
	}
}
