//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Extended Links Financial</summary>
	[PublishedModel("ExtendedLinks1")]
	public partial class ExtendedLinks1 : PublishedContentModel, IEbankItlink
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "ExtendedLinks1";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ExtendedLinks1, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ExtendedLinks1(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Description Image: This field will be appear below the image (Max Lenght:150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITDescriptionImage")]
		public string EbankItdescriptionImage => this.Value<string>("ebankITDescriptionImage");

		///<summary>
		/// Image: Image will be appear in list. This image must be in the   media. (this field is mandatory)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITImageLink")]
		public IPublishedContent EbankItimageLink => this.Value<IPublishedContent>("ebankITImageLink");

		///<summary>
		/// Link Text: This field will be appear below the image. (Max Lenght:150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebanKITTextButton")]
		public string EbanKittextButton => this.Value<string>("ebanKITTextButton");

		///<summary>
		/// Anchors Internal Link: The anchor the page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITAnchorsInternalLink")]
		public string EbankItanchorsInternalLink => EbankItlink.GetEbankItanchorsInternalLink(this);

		///<summary>
		/// Document: The document that will open. This document must be in the media
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITDocument")]
		public IPublishedContent EbankItdocument => EbankItlink.GetEbankItdocument(this);

		///<summary>
		/// External Link: Optional link to an external page. (http://website.com).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITExternalLink")]
		public string EbankItexternalLink => EbankItlink.GetEbankItexternalLink(this);

		///<summary>
		/// Internal Link: Link to a page on your site
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITInternalLink")]
		public IPublishedContent EbankItinternalLink => EbankItlink.GetEbankItinternalLink(this);

		///<summary>
		/// Text: This text only is shown in a List Links and the footer (Max length: 150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITLinkTitle")]
		public string EbankItlinkTitle => EbankItlink.GetEbankItlinkTitle(this);

		///<summary>
		/// Open New Tab: If you want the link open in new tab, you need selected this
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITOpenNewTab")]
		public bool EbankItopenNewTab => EbankItlink.GetEbankItopenNewTab(this);
	}
}
