//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "formSettings"
	/// <summary>Form Settings</summary>
	public partial interface IFormSettings : IPublishedContent
	{
		/// <summary>Button Label</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string EbankitButtonLabel { get; }

		/// <summary>Error Message</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string EbankitErrorMessage { get; }

		/// <summary>Main Subject</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string EbankItmainSubjectEmail { get; }

		/// <summary>Save Before Submit?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		bool EbankitSaveBeforeSubmit { get; }

		/// <summary>Save Before Submit Interval</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		int EbankitSaveBeforeSubmitInterval { get; }

		/// <summary>Subject Label</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string EbankitSubjectLabel { get; }

		/// <summary>Subject Values</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string EbankItsubjectValues { get; }

		/// <summary>Success Message</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string EbankitSuccessMessage { get; }
	}

	/// <summary>Form Settings</summary>
	[PublishedModel("formSettings")]
	public partial class FormSettings : PublishedContentModel, IFormSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "formSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FormSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public FormSettings(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Button Label: This label will appear in submit button and fly out tab.  (This field is mandatory /Max Length:15)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankitButtonLabel")]
		public string EbankitButtonLabel => GetEbankitButtonLabel(this);

		/// <summary>Static getter for Button Label</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetEbankitButtonLabel(IFormSettings that) => that.Value<string>("ebankitButtonLabel");

		///<summary>
		/// Error Message: Message will be appear when the form is not submitted successfully. (This filed is mandatory/ Max Length:150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankitErrorMessage")]
		public string EbankitErrorMessage => GetEbankitErrorMessage(this);

		/// <summary>Static getter for Error Message</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetEbankitErrorMessage(IFormSettings that) => that.Value<string>("ebankitErrorMessage");

		///<summary>
		/// Main Subject: This field will be sent as part of contract center subject (This Field is mandatory)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITMainSubjectEmail")]
		public string EbankItmainSubjectEmail => GetEbankItmainSubjectEmail(this);

		/// <summary>Static getter for Main Subject</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetEbankItmainSubjectEmail(IFormSettings that) => that.Value<string>("ebankITMainSubjectEmail");

		///<summary>
		/// Save Before Submit?: If this field is check, before the user click in submit button, the form will be save. If you fill this field, please fill next field 'Save Before Submit Interval'
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankitSaveBeforeSubmit")]
		public bool EbankitSaveBeforeSubmit => GetEbankitSaveBeforeSubmit(this);

		/// <summary>Static getter for Save Before Submit?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static bool GetEbankitSaveBeforeSubmit(IFormSettings that) => that.Value<bool>("ebankitSaveBeforeSubmit");

		///<summary>
		/// Save Before Submit Interval: Time, in seconds for the form submit without the user click in submit button.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankitSaveBeforeSubmitInterval")]
		public int EbankitSaveBeforeSubmitInterval => GetEbankitSaveBeforeSubmitInterval(this);

		/// <summary>Static getter for Save Before Submit Interval</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static int GetEbankitSaveBeforeSubmitInterval(IFormSettings that) => that.Value<int>("ebankitSaveBeforeSubmitInterval");

		///<summary>
		/// Subject Label: This label will be appear before the dropdown with all Subject Values. If you fill this field, please fill next field 'Subject Values'  (Max Length:150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankitSubjectLabel")]
		public string EbankitSubjectLabel => GetEbankitSubjectLabel(this);

		/// <summary>Static getter for Subject Label</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetEbankitSubjectLabel(IFormSettings that) => that.Value<string>("ebankitSubjectLabel");

		///<summary>
		/// Subject Values: Fill in this field with all the values ​​in the dropdown
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITSubjectValues")]
		public string EbankItsubjectValues => GetEbankItsubjectValues(this);

		/// <summary>Static getter for Subject Values</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetEbankItsubjectValues(IFormSettings that) => that.Value<string>("ebankITSubjectValues");

		///<summary>
		/// Success Message: Message will be appear when the form is submitted successfully. (This filed is  mandatory/ Max Length:150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankitSuccessMessage")]
		public string EbankitSuccessMessage => GetEbankitSuccessMessage(this);

		/// <summary>Static getter for Success Message</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetEbankitSuccessMessage(IFormSettings that) => that.Value<string>("ebankitSuccessMessage");
	}
}
