//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>HeroBodyInvestor</summary>
	[PublishedModel("heroBodyInvestor")]
	public partial class HeroBodyInvestor : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "heroBodyInvestor";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HeroBodyInvestor, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public HeroBodyInvestor(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Cancel button caption: Caption / dictionary key for the cancel button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("cancelButtonCaption")]
		public string CancelButtonCaption => this.Value<string>("cancelButtonCaption");

		///<summary>
		/// Cards: List of cards
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("cards")]
		public IEnumerable<NCdownload> Cards => this.Value<IEnumerable<NCdownload>>("cards");

		///<summary>
		/// Labels: List of labels
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("labels")]
		public IEnumerable<LabelItem> Labels => this.Value<IEnumerable<LabelItem>>("labels");

		///<summary>
		/// Open button caption: Caption/ dictionary key for the open button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("openButtonCaption")]
		public string OpenButtonCaption => this.Value<string>("openButtonCaption");

		///<summary>
		/// Signup Option Interests: List of interests separated by a ;
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("optionInterests")]
		public string OptionInterests => this.Value<string>("optionInterests");

		///<summary>
		/// Signup Option Roles: list of roles separated by  a ;
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("optionRoles")]
		public string OptionRoles => this.Value<string>("optionRoles");

		///<summary>
		/// Show sign up form: show / hide the sign up form
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("showSignUpForm")]
		public bool ShowSignUpForm => this.Value<bool>("showSignUpForm");

		///<summary>
		/// Signup Error message: The error message that will be displayed if the form is not submitted
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("signupErrorMessage")]
		public string SignupErrorMessage => this.Value<string>("signupErrorMessage");

		///<summary>
		/// Signup Form Title: Title on the signup form
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("signupFormTitle")]
		public IHtmlString SignupFormTitle => this.Value<IHtmlString>("signupFormTitle");

		///<summary>
		/// SignupSuccessMessage: Message displayed when the form is successfuly submitted
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("signupSuccessMessage")]
		public string SignupSuccessMessage => this.Value<string>("signupSuccessMessage");

		///<summary>
		/// Submit button caption: Caption/ dictionary ket for submit button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("submitButtonCaption")]
		public string SubmitButtonCaption => this.Value<string>("submitButtonCaption");
	}
}
