//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Hero Chest - Investments</summary>
	[PublishedModel("heroChestInvestments")]
	public partial class HeroChestInvestments : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "heroChestInvestments";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HeroChestInvestments, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public HeroChestInvestments(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// BenefitCards: The benefit card
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("benefitCards")]
		public IEnumerable<NCcard> BenefitCards => this.Value<IEnumerable<NCcard>>("benefitCards");

		///<summary>
		/// Benefits Description: Optional description of the benefits section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("benefitsDescription")]
		public string BenefitsDescription => this.Value<string>("benefitsDescription");

		///<summary>
		/// Benefits Title: Just a title introducing the Benefits section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("benefitsTitle")]
		public string BenefitsTitle => this.Value<string>("benefitsTitle");

		///<summary>
		/// Calculator Button Label: The label text to be displayed on the calculator button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("calculatorButtonLabel")]
		public string CalculatorButtonLabel => this.Value<string>("calculatorButtonLabel");

		///<summary>
		/// Calculator Intro: Paragraph to introduce the Calculator button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("calculatorIntro")]
		public string CalculatorIntro => this.Value<string>("calculatorIntro");

		///<summary>
		/// Rates Terms: List of terms and conditions around rates
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ratesTerms")]
		public IEnumerable<string> RatesTerms => this.Value<IEnumerable<string>>("ratesTerms");
	}
}
