//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>HeroFeetHome</summary>
	[PublishedModel("heroFeetHome")]
	public partial class HeroFeetHome : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "heroFeetHome";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HeroFeetHome, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public HeroFeetHome(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Contact Us Head Office Address Line 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("contactUsHeadOfficeAddressLine1")]
		public string ContactUsHeadOfficeAddressLine1 => this.Value<string>("contactUsHeadOfficeAddressLine1");

		///<summary>
		/// Contact Us Head Office Address Line 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("contactUsHeadOfficeAddressLine2")]
		public string ContactUsHeadOfficeAddressLine2 => this.Value<string>("contactUsHeadOfficeAddressLine2");

		///<summary>
		/// Contact Us Head Office Address Line 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("contactUsHeadOfficeAddressLine3")]
		public string ContactUsHeadOfficeAddressLine3 => this.Value<string>("contactUsHeadOfficeAddressLine3");

		///<summary>
		/// Contact Us Postal Address Line 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("contactUsPostalAddressLine1")]
		public string ContactUsPostalAddressLine1 => this.Value<string>("contactUsPostalAddressLine1");

		///<summary>
		/// Contact Us Postal Address Line 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("contactUsPostalAddressLine2")]
		public string ContactUsPostalAddressLine2 => this.Value<string>("contactUsPostalAddressLine2");

		///<summary>
		/// Contact Us Postal Address Line 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("contactUsPostalAddressLine3")]
		public string ContactUsPostalAddressLine3 => this.Value<string>("contactUsPostalAddressLine3");

		///<summary>
		/// Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("heading")]
		public string Heading => this.Value<string>("heading");

		///<summary>
		/// Links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("links")]
		public IEnumerable<FeetItem> Links => this.Value<IEnumerable<FeetItem>>("links");
	}
}
