//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Home</summary>
	[PublishedModel("home")]
	public partial class Home : PublishedContentModel, IPageSettings, ISearchEngine
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "home";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Home(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Bank Name: Select Bank
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("bankName")]
		public string BankName => this.Value<string>("bankName");

		///<summary>
		/// Call Me Back Cell Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("callMeBackCellNumber")]
		public string CallMeBackCellNumber => this.Value<string>("callMeBackCellNumber");

		///<summary>
		/// Call Me Back Different Location
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("callMeBackDifferentLocation")]
		public bool CallMeBackDifferentLocation => this.Value<bool>("callMeBackDifferentLocation");

		///<summary>
		/// Call Me Back ID Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("callMeBackID")]
		public string CallMeBackID => this.Value<string>("callMeBackID");

		///<summary>
		/// Call Me Back Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("callMeBackName")]
		public string CallMeBackName => this.Value<string>("callMeBackName");

		///<summary>
		/// Call Me Back Surname
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("callMeBackSurname")]
		public string CallMeBackSurname => this.Value<string>("callMeBackSurname");

		///<summary>
		/// cookie image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("cookieImage")]
		public IPublishedContent CookieImage => this.Value<IPublishedContent>("cookieImage");

		///<summary>
		/// Employment Sector: Select Employment Sector
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("employmentSector")]
		public string EmploymentSector => this.Value<string>("employmentSector");

		///<summary>
		/// Contact Type: Contact type information
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("contactType")]
		public string ContactType => PageSettings.GetContactType(this);

		///<summary>
		/// Floating Form
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("floatingForm")]
		public NCfloatingForm FloatingForm => PageSettings.GetFloatingForm(this);

		///<summary>
		/// productID: ID to uniquely Identify products
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("productID")]
		public string ProductID => PageSettings.GetProductID(this);

		///<summary>
		/// Product Subject: product subject for submittion
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("productSubject")]
		public string ProductSubject => PageSettings.GetProductSubject(this);

		///<summary>
		/// Alternate Image Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("alternateImageText")]
		public string AlternateImageText => SearchEngine.GetAlternateImageText(this);

		///<summary>
		/// Description_tag: This field will not be shown anywhere, it will be used in google indexing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("description_tag")]
		public string Description_tag => SearchEngine.GetDescription_tag(this);

		///<summary>
		/// Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("image")]
		public IPublishedContent Image => SearchEngine.GetImage(this);

		///<summary>
		/// keywords_tag: This field will not be shown anywhere, it will be used in google indexing {meta
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("keywords_tag")]
		public string Keywords_tag => SearchEngine.GetKeywords_tag(this);

		///<summary>
		/// robots_tag: Tag robots meta tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("robots_tag")]
		public string Robots_tag => SearchEngine.GetRobots_tag(this);

		///<summary>
		/// Security: Add yes if this page requires security and has a form
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("security")]
		public string Security => SearchEngine.GetSecurity(this);

		///<summary>
		/// title_tag: This field will not be shown anywhere, it will be used in google indexing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("title_tag")]
		public string Title_tag => SearchEngine.GetTitle_tag(this);
	}
}
