//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "nCCard"
	/// <summary>NC - Card</summary>
	public partial interface INCcard : IPublishedElement
	{
		/// <summary>Abstract Button</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string AbstractButton { get; }

		/// <summary>Abstract It</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string AbstractIt { get; }

		/// <summary>Image List And Descriptions</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IEnumerable<NCitemWithDescription> ImageListAndDescriptions { get; }

		/// <summary>Medium Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IHtmlString MediumDescription { get; }

		/// <summary>Card Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string NCcardDescription { get; }

		/// <summary>Card Icon</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IPublishedContent NCcardIcon { get; }

		/// <summary>NC Card Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string NCcardTitle { get; }

		/// <summary>Long Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IHtmlString NClongDescription { get; }
	}

	/// <summary>NC - Card</summary>
	[PublishedModel("nCCard")]
	public partial class NCcard : PublishedElementModel, INCcard
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "nCCard";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NCcard, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public NCcard(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Abstract Button: A button/ActionLink within a card
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("abstractButton")]
		public string AbstractButton => GetAbstractButton(this);

		/// <summary>Static getter for Abstract Button</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetAbstractButton(INCcard that) => that.Value<string>("abstractButton");

		///<summary>
		/// Abstract It: Button Link To External
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("abstractIt")]
		public string AbstractIt => GetAbstractIt(this);

		/// <summary>Static getter for Abstract It</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetAbstractIt(INCcard that) => that.Value<string>("abstractIt");

		///<summary>
		/// Image List And Descriptions: Image List And Descriptions
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("imageListAndDescriptions")]
		public IEnumerable<NCitemWithDescription> ImageListAndDescriptions => GetImageListAndDescriptions(this);

		/// <summary>Static getter for Image List And Descriptions</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IEnumerable<NCitemWithDescription> GetImageListAndDescriptions(INCcard that) => that.Value<IEnumerable<NCitemWithDescription>>("imageListAndDescriptions");

		///<summary>
		/// Medium Description: This is a control for extending description on the page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("mediumDescription")]
		public IHtmlString MediumDescription => GetMediumDescription(this);

		/// <summary>Static getter for Medium Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IHtmlString GetMediumDescription(INCcard that) => that.Value<IHtmlString>("mediumDescription");

		///<summary>
		/// Card Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("nCcardDescription")]
		public string NCcardDescription => GetNCcardDescription(this);

		/// <summary>Static getter for Card Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetNCcardDescription(INCcard that) => that.Value<string>("nCcardDescription");

		///<summary>
		/// Card Icon
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("nCcardIcon")]
		public IPublishedContent NCcardIcon => GetNCcardIcon(this);

		/// <summary>Static getter for Card Icon</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedContent GetNCcardIcon(INCcard that) => that.Value<IPublishedContent>("nCcardIcon");

		///<summary>
		/// NC Card Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("nCcardTitle")]
		public string NCcardTitle => GetNCcardTitle(this);

		/// <summary>Static getter for NC Card Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetNCcardTitle(INCcard that) => that.Value<string>("nCcardTitle");

		///<summary>
		/// Long Description: Rich Textbox for descriptions that have mixed media and are long
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("nClongDescription")]
		public IHtmlString NClongDescription => GetNClongDescription(this);

		/// <summary>Static getter for Long Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IHtmlString GetNClongDescription(INCcard that) => that.Value<IHtmlString>("nClongDescription");
	}
}
