//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>NC - Compliance Elements</summary>
	[PublishedModel("nCComplianceElements")]
	public partial class NCcomplianceElements : PublishedElementModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "nCComplianceElements";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NCcomplianceElements, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public NCcomplianceElements(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// NC Legal Document Compliance Link: First Legal Document Compliance Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("nClegalDocumentComplianceLink")]
		public IEnumerable<StructureTextAndButton> NClegalDocumentComplianceLink => this.Value<IEnumerable<StructureTextAndButton>>("nClegalDocumentComplianceLink");

		///<summary>
		/// Legal Document Compliance Link 2: Second Legal Document Compliance Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("nClegalDocumentComplianceLink2")]
		public IEnumerable<StructureTextAndButton> NClegalDocumentComplianceLink2 => this.Value<IEnumerable<StructureTextAndButton>>("nClegalDocumentComplianceLink2");

		///<summary>
		/// Legal Document Compliance Text: Legal Document Compliance Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("nClegalDocumentComplianceText")]
		public string NClegalDocumentComplianceText => this.Value<string>("nClegalDocumentComplianceText");
	}
}
