//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "nCDocumentTypeTitleAndDescription"
	/// <summary>NC - Document Type Title And Description</summary>
	public partial interface INCdocumentTypeTitleAndDescription : IPublishedElement
	{
		/// <summary>Body Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IHtmlString NCbodyDescription { get; }

		/// <summary>Body Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string NCbodyTitle { get; }
	}

	/// <summary>NC - Document Type Title And Description</summary>
	[PublishedModel("nCDocumentTypeTitleAndDescription")]
	public partial class NCdocumentTypeTitleAndDescription : PublishedElementModel, INCdocumentTypeTitleAndDescription
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "nCDocumentTypeTitleAndDescription";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NCdocumentTypeTitleAndDescription, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public NCdocumentTypeTitleAndDescription(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Body Description: A Generic Body Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("nCbodyDescription")]
		public IHtmlString NCbodyDescription => GetNCbodyDescription(this);

		/// <summary>Static getter for Body Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IHtmlString GetNCbodyDescription(INCdocumentTypeTitleAndDescription that) => that.Value<IHtmlString>("nCbodyDescription");

		///<summary>
		/// Body Title: A Generic Body Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("nCbodyTitle")]
		public string NCbodyTitle => GetNCbodyTitle(this);

		/// <summary>Static getter for Body Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetNCbodyTitle(INCdocumentTypeTitleAndDescription that) => that.Value<string>("nCbodyTitle");
	}
}
