//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "nCFloatingForm"
	/// <summary>NC - Floating Form</summary>
	public partial interface INCfloatingForm : IPublishedElement
	{
		/// <summary>Call me back button text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string CallMeBackButtonText { get; }

		/// <summary>Call me back visible</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		bool CallMeBackVisible { get; }

		/// <summary>External link text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string ExternalLabel { get; }

		/// <summary>External link visible</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		bool ExternalLinkVisible { get; }

		/// <summary>External link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string LinkExternal { get; }

		/// <summary>Open As Default?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		bool OpenAsDefault { get; }

		/// <summary>Product Identification</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string ProductIdentification { get; }

		/// <summary>Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string Title { get; }
	}

	/// <summary>NC - Floating Form</summary>
	[PublishedModel("nCFloatingForm")]
	public partial class NCfloatingForm : PublishedElementModel, INCfloatingForm
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "nCFloatingForm";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NCfloatingForm, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public NCfloatingForm(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Call me back button text: Text in the button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("callMeBackButtonText")]
		public string CallMeBackButtonText => GetCallMeBackButtonText(this);

		/// <summary>Static getter for Call me back button text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetCallMeBackButtonText(INCfloatingForm that) => that.Value<string>("callMeBackButtonText");

		///<summary>
		/// Call me back visible: Hide or show call me back button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("callMeBackVisible")]
		public bool CallMeBackVisible => GetCallMeBackVisible(this);

		/// <summary>Static getter for Call me back visible</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static bool GetCallMeBackVisible(INCfloatingForm that) => that.Value<bool>("callMeBackVisible");

		///<summary>
		/// External link text: Text for the external link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("externalLabel")]
		public string ExternalLabel => GetExternalLabel(this);

		/// <summary>Static getter for External link text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetExternalLabel(INCfloatingForm that) => that.Value<string>("externalLabel");

		///<summary>
		/// External link visible: Hide or show external links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("externalLinkVisible")]
		public bool ExternalLinkVisible => GetExternalLinkVisible(this);

		/// <summary>Static getter for External link visible</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static bool GetExternalLinkVisible(INCfloatingForm that) => that.Value<bool>("externalLinkVisible");

		///<summary>
		/// External link: External links from the website
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("linkExternal")]
		public string LinkExternal => GetLinkExternal(this);

		/// <summary>Static getter for External link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetLinkExternal(INCfloatingForm that) => that.Value<string>("linkExternal");

		///<summary>
		/// Open As Default?: Open the floating form on page load.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("openAsDefault")]
		public bool OpenAsDefault => GetOpenAsDefault(this);

		/// <summary>Static getter for Open As Default?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static bool GetOpenAsDefault(INCfloatingForm that) => that.Value<bool>("openAsDefault");

		///<summary>
		/// Product Identification: For google analytics tracking
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("productIdentification")]
		public string ProductIdentification => GetProductIdentification(this);

		/// <summary>Static getter for Product Identification</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetProductIdentification(INCfloatingForm that) => that.Value<string>("productIdentification");

		///<summary>
		/// Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("title")]
		public string Title => GetTitle(this);

		/// <summary>Static getter for Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetTitle(INCfloatingForm that) => that.Value<string>("title");
	}
}
