//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Quick Loans</summary>
	[PublishedModel("quickLoans")]
	public partial class QuickLoans : PublishedContentModel, ISearchEngine
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "quickLoans";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<QuickLoans, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public QuickLoans(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Quick Loans Bank: Bank Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansBank")]
		public string QuickLoansBank => this.Value<string>("quickLoansBank");

		///<summary>
		/// Quick Loans Bank Label: This is the label for the Bank field
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansBankLabel")]
		public string QuickLoansBankLabel => this.Value<string>("quickLoansBankLabel");

		///<summary>
		/// Quick Loans Bank Statement: Bank statement
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansBankStatement")]
		public string QuickLoansBankStatement => this.Value<string>("quickLoansBankStatement");

		///<summary>
		/// Quick Loans Bank Statement Label: This is the label for the Bank Statement field
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansBankStatementLabel")]
		public string QuickLoansBankStatementLabel => this.Value<string>("quickLoansBankStatementLabel");

		///<summary>
		/// Quick Loans Cellphone No: Cellphone number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansCellphoneNo")]
		public string QuickLoansCellphoneNo => this.Value<string>("quickLoansCellphoneNo");

		///<summary>
		/// Quick Loans Child Maintenance: Child maintenance
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansChildMaintenance")]
		public string QuickLoansChildMaintenance => this.Value<string>("quickLoansChildMaintenance");

		///<summary>
		/// Quick Loans Child Maintenance Expenses: Child maintenance expenses
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansChildMaintenanceExpenses")]
		public string QuickLoansChildMaintenanceExpenses => this.Value<string>("quickLoansChildMaintenanceExpenses");

		///<summary>
		/// Quick Loans Child Maintenance Label: This is the label for the Child Maintenance field
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansChildMaintenanceLabel")]
		public string QuickLoansChildMaintenanceLabel => this.Value<string>("quickLoansChildMaintenanceLabel");

		///<summary>
		/// Quick Loans Email: Email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansEmail")]
		public string QuickLoansEmail => this.Value<string>("quickLoansEmail");

		///<summary>
		/// Quick Loans Employer: Employer
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansEmployer")]
		public string QuickLoansEmployer => this.Value<string>("quickLoansEmployer");

		///<summary>
		/// Quick Loans Employment Sector
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansEmploymentSector")]
		public string QuickLoansEmploymentSector => this.Value<string>("quickLoansEmploymentSector");

		///<summary>
		/// Quick Loans Employment Start Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansEmploymentStartDate")]
		public string QuickLoansEmploymentStartDate => this.Value<string>("quickLoansEmploymentStartDate");

		///<summary>
		/// Quick Loans Gross Salary Before Tax
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansGrossSalaryBeforeTax")]
		public string QuickLoansGrossSalaryBeforeTax => this.Value<string>("quickLoansGrossSalaryBeforeTax");

		///<summary>
		/// Quick Loans ID Number: SA ID number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansIDNumber")]
		public string QuickLoansIdnumber => this.Value<string>("quickLoansIDNumber");

		///<summary>
		/// Quick Loans Living Expense: Living expense
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansLivingExpense")]
		public string QuickLoansLivingExpense => this.Value<string>("quickLoansLivingExpense");

		///<summary>
		/// Quick Loans Looking For
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansLookingFor")]
		public string QuickLoansLookingFor => this.Value<string>("quickLoansLookingFor");

		///<summary>
		/// Quick Loans Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansName")]
		public string QuickLoansName => this.Value<string>("quickLoansName");

		///<summary>
		/// Quick Loans Net Income: Net income
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansNetIncome")]
		public string QuickLoansNetIncome => this.Value<string>("quickLoansNetIncome");

		///<summary>
		/// Quick Loans One Time PIN: One time PIN
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansOneTimePIN")]
		public string QuickLoansOneTimePin => this.Value<string>("quickLoansOneTimePIN");

		///<summary>
		/// Quick Loans One Time Pin Message: Message displayed to notify the user of a PIN sent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansOneTimePinMessage")]
		public string QuickLoansOneTimePinMessage => this.Value<string>("quickLoansOneTimePinMessage");

		///<summary>
		/// Quick Loans Product Market Info
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansProductMarketInfo")]
		public string QuickLoansProductMarketInfo => this.Value<string>("quickLoansProductMarketInfo");

		///<summary>
		/// Quick Loans Reference Check Warning
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansReferenceCheckWarning")]
		public IHtmlString QuickLoansReferenceCheckWarning => this.Value<IHtmlString>("quickLoansReferenceCheckWarning");

		///<summary>
		/// Quick Loans Salary Frequency: SalaryFrequency
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansSalaryFrequency")]
		public string QuickLoansSalaryFrequency => this.Value<string>("quickLoansSalaryFrequency");

		///<summary>
		/// Quick Loans Salary Frequency Label: This is the label for the Salary Frequency field
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansSalaryFrequencyLabel")]
		public string QuickLoansSalaryFrequencyLabel => this.Value<string>("quickLoansSalaryFrequencyLabel");

		///<summary>
		/// Quick Loans Surname: Surname
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("quickLoansSurname")]
		public string QuickLoansSurname => this.Value<string>("quickLoansSurname");

		///<summary>
		/// Step1Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step1Heading")]
		public IHtmlString Step1Heading => this.Value<IHtmlString>("step1Heading");

		///<summary>
		/// Step1Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step1Name")]
		public string Step1Name => this.Value<string>("step1Name");

		///<summary>
		/// Step1ShortDescription
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step1ShortDescription")]
		public string Step1ShortDescription => this.Value<string>("step1ShortDescription");

		///<summary>
		/// Step2 Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step2Heading")]
		public IHtmlString Step2Heading => this.Value<IHtmlString>("step2Heading");

		///<summary>
		/// Step2Name: Name in step 2 tab
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step2Name")]
		public string Step2Name => this.Value<string>("step2Name");

		///<summary>
		/// Step2 Short Description: Short description of step 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step2ShortDescription")]
		public string Step2ShortDescription => this.Value<string>("step2ShortDescription");

		///<summary>
		/// Step3 Heading: Heading of step 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step3Heading")]
		public IHtmlString Step3Heading => this.Value<IHtmlString>("step3Heading");

		///<summary>
		/// Step3 Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step3Name")]
		public string Step3Name => this.Value<string>("step3Name");

		///<summary>
		/// Step3 Short Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step3ShortDescription")]
		public string Step3ShortDescription => this.Value<string>("step3ShortDescription");

		///<summary>
		/// Step4 Heading: Headin of step 4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step4Heading")]
		public IHtmlString Step4Heading => this.Value<IHtmlString>("step4Heading");

		///<summary>
		/// Step4 Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step4Name")]
		public string Step4Name => this.Value<string>("step4Name");

		///<summary>
		/// Step4 Short Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step4ShortDescription")]
		public string Step4ShortDescription => this.Value<string>("step4ShortDescription");

		///<summary>
		/// Step5 Heading: Heading of step 5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step5Heading")]
		public IHtmlString Step5Heading => this.Value<IHtmlString>("step5Heading");

		///<summary>
		/// Step5 Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step5Name")]
		public string Step5Name => this.Value<string>("step5Name");

		///<summary>
		/// Step5 Short Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step5ShortDescription")]
		public string Step5ShortDescription => this.Value<string>("step5ShortDescription");

		///<summary>
		/// Step 6 Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step6Heading")]
		public IHtmlString Step6Heading => this.Value<IHtmlString>("step6Heading");

		///<summary>
		/// Step 6: Name of the step (top of tab)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step6Name")]
		public string Step6Name => this.Value<string>("step6Name");

		///<summary>
		/// Step 6 Short Description: Short description below the tab name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("step6ShortDescription")]
		public string Step6ShortDescription => this.Value<string>("step6ShortDescription");

		///<summary>
		/// Alternate Image Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("alternateImageText")]
		public string AlternateImageText => SearchEngine.GetAlternateImageText(this);

		///<summary>
		/// Description_tag: This field will not be shown anywhere, it will be used in google indexing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("description_tag")]
		public string Description_tag => SearchEngine.GetDescription_tag(this);

		///<summary>
		/// Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("image")]
		public IPublishedContent Image => SearchEngine.GetImage(this);

		///<summary>
		/// keywords_tag: This field will not be shown anywhere, it will be used in google indexing {meta
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("keywords_tag")]
		public string Keywords_tag => SearchEngine.GetKeywords_tag(this);

		///<summary>
		/// robots_tag: Tag robots meta tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("robots_tag")]
		public string Robots_tag => SearchEngine.GetRobots_tag(this);

		///<summary>
		/// Security: Add yes if this page requires security and has a form
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("security")]
		public string Security => SearchEngine.GetSecurity(this);

		///<summary>
		/// title_tag: This field will not be shown anywhere, it will be used in google indexing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("title_tag")]
		public string Title_tag => SearchEngine.GetTitle_tag(this);
	}
}
