//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Structure Body Text with Image and Link</summary>
	[PublishedModel("structureBodyTextWithImageAndLink")]
	public partial class StructureBodyTextWithImageAndLink : PublishedContentModel, IEbankItgeneralProperties
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "structureBodyTextWithImageAndLink";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StructureBodyTextWithImageAndLink, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public StructureBodyTextWithImageAndLink(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Image: Image will be appear in List. This image must be in the  media.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITImage")]
		public IPublishedContent EbankItimage => this.Value<IPublishedContent>("ebankITImage");

		///<summary>
		/// Section Hero Body Background: Section Hero Body Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("sectionHeroBodyBackground")]
		public IPublishedContent SectionHeroBodyBackground => this.Value<IPublishedContent>("sectionHeroBodyBackground");

		///<summary>
		/// Section Hero Body Description: Section Hero Body Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("sectionHeroBodyDescription")]
		public IHtmlString SectionHeroBodyDescription => this.Value<IHtmlString>("sectionHeroBodyDescription");

		///<summary>
		/// Button Link: Section Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("sectionLink")]
		public IEnumerable<Umbraco.Web.Models.Link> SectionLink => this.Value<IEnumerable<Umbraco.Web.Models.Link>>("sectionLink");

		///<summary>
		/// Section Order
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("sectionOrder")]
		public string SectionOrder => this.Value<string>("sectionOrder");

		///<summary>
		/// Content: The first section of text in page or section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITContent")]
		public IHtmlString EbankItcontent => EbankItgeneralProperties.GetEbankItcontent(this);

		///<summary>
		/// Title: Title of page or section  (Max Length:150)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ebankITTitle")]
		public string EbankIttitle => EbankItgeneralProperties.GetEbankIttitle(this);
	}
}
