//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Structure Featured Product</summary>
	[PublishedModel("structureFeaturedProduct")]
	public partial class StructureFeaturedProduct : PublishedElementModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "structureFeaturedProduct";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StructureFeaturedProduct, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public StructureFeaturedProduct(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Featured Product Button Label
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("featuredProductButtonLabel")]
		public string FeaturedProductButtonLabel => this.Value<string>("featuredProductButtonLabel");

		///<summary>
		/// Featured Product Button Redirect Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("featuredProductButtonRedirectLink")]
		public IPublishedContent FeaturedProductButtonRedirectLink => this.Value<IPublishedContent>("featuredProductButtonRedirectLink");

		///<summary>
		/// Featured Product Cover Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("featuredProductCoverImage")]
		public IPublishedContent FeaturedProductCoverImage => this.Value<IPublishedContent>("featuredProductCoverImage");

		///<summary>
		/// Featured Product Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("featuredProductDescription")]
		public string FeaturedProductDescription => this.Value<string>("featuredProductDescription");

		///<summary>
		/// Featured Product Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("featuredProductHeading")]
		public string FeaturedProductHeading => this.Value<string>("featuredProductHeading");

		///<summary>
		/// Featured Product Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("featuredProductTitle")]
		public string FeaturedProductTitle => this.Value<string>("featuredProductTitle");

		///<summary>
		/// In Page Linking
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("inPageLinking")]
		public IEnumerable<Umbraco.Web.Models.Link> InPageLinking => this.Value<IEnumerable<Umbraco.Web.Models.Link>>("inPageLinking");
	}
}
