//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "structureTextAndButton"
	/// <summary>Structure Text And Button</summary>
	public partial interface IStructureTextAndButton : IPublishedElement
	{
		/// <summary>Download Button Redirect Link2</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IPublishedContent DownloadButtonRedirectLink2 { get; }

		/// <summary>Download Text Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string DownloadTextDescription { get; }
	}

	/// <summary>Structure Text And Button</summary>
	[PublishedModel("structureTextAndButton")]
	public partial class StructureTextAndButton : PublishedElementModel, IStructureTextAndButton
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "structureTextAndButton";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StructureTextAndButton, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public StructureTextAndButton(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Download Button Redirect Link2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("downloadButtonRedirectLink2")]
		public IPublishedContent DownloadButtonRedirectLink2 => GetDownloadButtonRedirectLink2(this);

		/// <summary>Static getter for Download Button Redirect Link2</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedContent GetDownloadButtonRedirectLink2(IStructureTextAndButton that) => that.Value<IPublishedContent>("downloadButtonRedirectLink2");

		///<summary>
		/// Download Text Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("downloadTextDescription")]
		public string DownloadTextDescription => GetDownloadTextDescription(this);

		/// <summary>Static getter for Download Text Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetDownloadTextDescription(IStructureTextAndButton that) => that.Value<string>("downloadTextDescription");
	}
}
