//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Structure Product Information</summary>
	[PublishedModel("structureProductInformation")]
	public partial class StructureProductInformation : PublishedElementModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "structureProductInformation";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StructureProductInformation, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public StructureProductInformation(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Campaign Highlight Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("campaignHighlightDescription")]
		public string CampaignHighlightDescription => this.Value<string>("campaignHighlightDescription");

		///<summary>
		/// Campaign Product Apply Now Button Label
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("campaignProductApplyNowButtonLabel")]
		public string CampaignProductApplyNowButtonLabel => this.Value<string>("campaignProductApplyNowButtonLabel");

		///<summary>
		/// Campaign Product Apply Now Button Redirect Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("campaignProductApplyNowButtonRedirectLink")]
		public IPublishedContent CampaignProductApplyNowButtonRedirectLink => this.Value<IPublishedContent>("campaignProductApplyNowButtonRedirectLink");

		///<summary>
		/// Campaign Product Benefit
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("campaignProductBenefit")]
		public IEnumerable<StructureBenefit> CampaignProductBenefit => this.Value<IEnumerable<StructureBenefit>>("campaignProductBenefit");

		///<summary>
		/// Campaign Product Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("campaignProductDescription")]
		public string CampaignProductDescription => this.Value<string>("campaignProductDescription");

		///<summary>
		/// Campaign Product Highlight
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("campaignProductHighlight")]
		public string CampaignProductHighlight => this.Value<string>("campaignProductHighlight");

		///<summary>
		/// CampaignProductImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("campaignProductImage")]
		public IPublishedContent CampaignProductImage => this.Value<IPublishedContent>("campaignProductImage");

		///<summary>
		/// Campaign Product Learn More Button Label
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("campaignProductLearnMoreButtonLabel")]
		public string CampaignProductLearnMoreButtonLabel => this.Value<string>("campaignProductLearnMoreButtonLabel");

		///<summary>
		/// Campaign Product Learn More Button Redirect Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("campaignProductLearnMoreButtonRedirectLink")]
		public IPublishedContent CampaignProductLearnMoreButtonRedirectLink => this.Value<IPublishedContent>("campaignProductLearnMoreButtonRedirectLink");

		///<summary>
		/// Campaign Product Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("campaignProductTitle")]
		public string CampaignProductTitle => this.Value<string>("campaignProductTitle");

		///<summary>
		/// In Page Linking
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("inPageLinking")]
		public IEnumerable<Umbraco.Web.Models.Link> InPageLinking => this.Value<IEnumerable<Umbraco.Web.Models.Link>>("inPageLinking");

		///<summary>
		/// Learn More Button Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("learnMoreButtonLink")]
		public IEnumerable<Umbraco.Web.Models.Link> LearnMoreButtonLink => this.Value<IEnumerable<Umbraco.Web.Models.Link>>("learnMoreButtonLink");
	}
}
