//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Talk to us</summary>
	[PublishedModel("talkToUs")]
	public partial class TalkToUs : PublishedContentModel, ISearchEngine
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "talkToUs";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TalkToUs, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public TalkToUs(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Important Numbers
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("importantNumbers")]
		public IEnumerable<NCcontactItem> ImportantNumbers => this.Value<IEnumerable<NCcontactItem>>("importantNumbers");

		///<summary>
		/// Support Centre Contacts
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("supportCentreContacts")]
		public IEnumerable<NCcontactItem> SupportCentreContacts => this.Value<IEnumerable<NCcontactItem>>("supportCentreContacts");

		///<summary>
		/// urlIframe: Url with the location or url of video/form (This field is mandatory)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("urlIframe")]
		public string UrlIframe => this.Value<string>("urlIframe");

		///<summary>
		/// Alternate Image Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("alternateImageText")]
		public string AlternateImageText => SearchEngine.GetAlternateImageText(this);

		///<summary>
		/// Description_tag: This field will not be shown anywhere, it will be used in google indexing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("description_tag")]
		public string Description_tag => SearchEngine.GetDescription_tag(this);

		///<summary>
		/// Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("image")]
		public IPublishedContent Image => SearchEngine.GetImage(this);

		///<summary>
		/// keywords_tag: This field will not be shown anywhere, it will be used in google indexing {meta
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("keywords_tag")]
		public string Keywords_tag => SearchEngine.GetKeywords_tag(this);

		///<summary>
		/// robots_tag: Tag robots meta tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("robots_tag")]
		public string Robots_tag => SearchEngine.GetRobots_tag(this);

		///<summary>
		/// Security: Add yes if this page requires security and has a form
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("security")]
		public string Security => SearchEngine.GetSecurity(this);

		///<summary>
		/// title_tag: This field will not be shown anywhere, it will be used in google indexing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("title_tag")]
		public string Title_tag => SearchEngine.GetTitle_tag(this);
	}
}
