//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Value Added Deal Tab</summary>
	[PublishedModel("valueAddedDeal")]
	public partial class ValueAddedDeal : PublishedContentModel, ITabBase
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "valueAddedDeal";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ValueAddedDeal, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ValueAddedDeal(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Catalog Rich Items: Used when the catalog item contains complex content. ie: picture, description and/or button with links.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("catalogCards")]
		public IEnumerable<StructureVadtechDeals> CatalogCards => this.Value<IEnumerable<StructureVadtechDeals>>("catalogCards");

		///<summary>
		/// Catalog Images: Used when the catalog display simple images or icons
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("catalogImages")]
		public IEnumerable<IPublishedContent> CatalogImages => this.Value<IEnumerable<IPublishedContent>>("catalogImages");

		///<summary>
		/// Related Links: Related links to other documents in the system
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("relatedLinks")]
		public IEnumerable<Umbraco.Web.Models.Link> RelatedLinks => this.Value<IEnumerable<Umbraco.Web.Models.Link>>("relatedLinks");

		///<summary>
		/// Tab buttons: Optional buttons the tab might have.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("tabButtons")]
		public IEnumerable<NCabstractButton> TabButtons => this.Value<IEnumerable<NCabstractButton>>("tabButtons");

		///<summary>
		/// Tab type: Select the tab type - this will determine how the content is displayed
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("tabType")]
		public string TabType => this.Value<string>("tabType");

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("description")]
		public string Description => TabBase.GetDescription(this);

		///<summary>
		/// Tab Icon
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("tabIcon")]
		public IPublishedContent TabIcon => TabBase.GetTabIcon(this);

		///<summary>
		/// Title: The title of the tab
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("title")]
		public string Title => TabBase.GetTitle(this);
	}
}
